"""initial schema

Revision ID: 0cb824e923d0
Revises:
Create Date: 2026-06-17 16:32:39.682222
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision = '0cb824e923d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('target_user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_logs_action'), 'admin_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_admin_id'), 'admin_audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_target_user_id'), 'admin_audit_logs', ['target_user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('original_name', sa.String(length=500), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('oss_key', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('upload_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sync_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oss_key')
    )
    op.create_index(op.f('ix_documents_brand'), 'documents', ['brand'], unique=False)
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.create_table('download_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('resource_id', sa.BigInteger(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_logs_created_at'), 'download_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_download_logs_resource_id'), 'download_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_download_logs_resource_type'), 'download_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_download_logs_user_id'), 'download_logs', ['user_id'], unique=False)
    op.create_table('login_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.Column('geo_location', sa.String(length=255), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ip_address', 'user_agent', name='uq_login_session_device')
    )
    op.create_index(op.f('ix_login_sessions_is_active'), 'login_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_login_sessions_last_active_at'), 'login_sessions', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_login_sessions_user_id'), 'login_sessions', ['user_id'], unique=False)
    op.create_table('portal_contents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_contents_is_active'), 'portal_contents', ['is_active'], unique=False)
    op.create_index(op.f('ix_portal_contents_section'), 'portal_contents', ['section'], unique=False)
    op.create_table('sms_codes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(), nullable=False),
    sa.Column('verify_attempts', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_codes_created_at'), 'sms_codes', ['created_at'], unique=False)
    op.create_index(op.f('ix_sms_codes_phone'), 'sms_codes', ['phone'], unique=False)
    op.create_table('software',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('original_name', sa.String(length=500), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('latest_version', sa.String(length=100), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_software_brand'), 'software', ['brand'], unique=False)
    op.create_index(op.f('ix_software_category'), 'software', ['category'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sync_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_document_id'), 'sync_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_sync_logs_status'), 'sync_logs', ['status'], unique=False)
    op.create_table('system_configs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_config_key'), 'system_configs', ['config_key'], unique=True)
    op.create_table('token_blacklist',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_expires_at'), 'token_blacklist', ['expires_at'], unique=False)
    op.create_index(op.f('ix_token_blacklist_jti'), 'token_blacklist', ['jti'], unique=True)
    op.create_index(op.f('ix_token_blacklist_user_id'), 'token_blacklist', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(), nullable=True),
    sa.Column('blacklisted_by', sa.BigInteger(), nullable=True),
    sa.Column('tokens_invalidated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blacklisted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('software_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('software_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('oss_key', sa.String(length=500), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('upload_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oss_key')
    )
    op.create_index(op.f('ix_software_versions_file_hash'), 'software_versions', ['file_hash'], unique=False)
    op.create_index(op.f('ix_software_versions_software_id'), 'software_versions', ['software_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_software_versions_software_id'), table_name='software_versions')
    op.drop_index(op.f('ix_software_versions_file_hash'), table_name='software_versions')
    op.drop_table('software_versions')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_token_blacklist_user_id'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_jti'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_expires_at'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index(op.f('ix_system_configs_config_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_sync_logs_status'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_document_id'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_software_category'), table_name='software')
    op.drop_index(op.f('ix_software_brand'), table_name='software')
    op.drop_table('software')
    op.drop_index(op.f('ix_sms_codes_phone'), table_name='sms_codes')
    op.drop_index(op.f('ix_sms_codes_created_at'), table_name='sms_codes')
    op.drop_table('sms_codes')
    op.drop_index(op.f('ix_portal_contents_section'), table_name='portal_contents')
    op.drop_index(op.f('ix_portal_contents_is_active'), table_name='portal_contents')
    op.drop_table('portal_contents')
    op.drop_index(op.f('ix_login_sessions_user_id'), table_name='login_sessions')
    op.drop_index(op.f('ix_login_sessions_last_active_at'), table_name='login_sessions')
    op.drop_index(op.f('ix_login_sessions_is_active'), table_name='login_sessions')
    op.drop_table('login_sessions')
    op.drop_index(op.f('ix_download_logs_user_id'), table_name='download_logs')
    op.drop_index(op.f('ix_download_logs_resource_type'), table_name='download_logs')
    op.drop_index(op.f('ix_download_logs_resource_id'), table_name='download_logs')
    op.drop_index(op.f('ix_download_logs_created_at'), table_name='download_logs')
    op.drop_table('download_logs')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.drop_index(op.f('ix_documents_brand'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_admin_audit_logs_target_user_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_admin_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_action'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    # ### end Alembic commands ###
