"""add brand mapping seed data for keyence and inovance

Revision ID: 20260630_add_keyence_inovance_mappings
Revises: 20260630_add_message_feedback
Create Date: 2026-06-30
"""
from alembic import op

revision = "20260630_add_keyence_inovance_mappings"
down_revision = "20260630_add_message_feedback"
branch_labels = None
depends_on = None


def upgrade():
    # ── Siemens → Keyence KV-8000 ──────────────────────────────────────────
    op.execute("""
        INSERT INTO brand_mappings (source_brand, target_brand, item_type, source_value, target_value, description) VALUES
        ('siemens','keyence','io',
         'Ix.y (I0.0~I127.7)',
         'X0~X511 (十六进制输入继电器，按模块槽位分配)',
         '数字量输入: Siemens Ix.y 点位 → Keyence X 输入继电器(十六进制编号，需查模块 I/O 映射表)'),
        ('siemens','keyence','io',
         'Qx.y (Q0.0~Q127.7)',
         'Y0~Y511 (十六进制输出继电器，按模块槽位分配)',
         '数字量输出: Siemens Qx.y → Keyence Y 输出继电器(十六进制编号)'),
        ('siemens','keyence','memory',
         'Mx.y (Merker位, M0.0~M8191.7)',
         'R0~R59999 (内部继电器，按位编号)',
         '位存储器: Siemens M 位 → Keyence R 内部继电器(无字节偏移，直接按位顺序编号)'),
        ('siemens','keyence','memory',
         'MWx (Merker Word 16位)',
         'DM0~DM65535 (数据存储器，16位字)',
         '字存储器: Siemens MWx → Keyence DM(Data Memory)；地址需重新规划，不直接对应'),
        ('siemens','keyence','memory',
         'MDx (Merker DWord 32位)',
         'DM x + DM x+1 (两个连续 DM 存储 32位)',
         '双字: Siemens MDx 32位 → Keyence 两个连续 DM 寄存器；小端序，低16位存低地址'),
        ('siemens','keyence','timer',
         'T0 (S_ODT 接通延时, 100ms分辨率)',
         'TM0~TM3999 (定时器存储器, 100ms 基准)',
         '定时器: Siemens T(100ms) → Keyence TM；精度一致；KV 支持 10ms/1ms 高精度定时器'),
        ('siemens','keyence','counter',
         'C0 (CTU 加计数 / CTD 减计数)',
         'CM0~CM3999 (计数器存储器，加计数)',
         '计数器: Siemens CTU → Keyence CM；Keyence CM 默认为加计数，可软件配置减计数'),
        ('siemens','keyence','communication',
         'PROFINET (IEC 61158, 端口102, 100Mbps+)',
         'EtherNet/IP (端口44818/UDP 2222, KV-8000 内置)',
         '工业以太网: PROFINET → EtherNet/IP；KV-8000 原生支持 EIP，PROFINET 需外部适配器'),
        ('siemens','keyence','communication',
         'S7 协议 (ISO on TCP, 端口102)',
         'KV 通信协议 (TCP 端口8501 / UDP 8500, 专有)',
         '专有通信: Siemens S7 → Keyence KV 协议；两者均支持上位机直接读写 PLC 内存'),
        ('siemens','keyence','communication',
         'Modbus TCP (标准, 端口502)',
         'Modbus TCP (标准, 端口502)',
         '两者均完整支持 Modbus TCP，功能码 03/06/16 通用；Keyence 需在 KV-STUDIO 启用 Modbus 服务'),
        ('siemens','keyence','instruction',
         'MOVE (数据传送)',
         'MOV (传送指令)',
         '数据传送: Siemens MOVE → Keyence MOV；功能完全一致'),
        ('siemens','keyence','instruction',
         'ADD_I / SUB_I (16位整数加减)',
         'ADD / SUB (整数加减)',
         '整数运算: Siemens ADD_I/SUB_I → Keyence ADD/SUB；操作数格式有所不同'),
        ('siemens','keyence','instruction',
         'CMP_EQ / CMP_LT / CMP_GT (比较)',
         'CMP= / CMP< / CMP> (比较指令)',
         '比较指令: Siemens 比较 Box → Keyence CMP 系列；结果置 R 继电器'),
        ('siemens','keyence','instruction',
         'FB/FC 调用 (函数块/函数)',
         '宏程序 (MACRO) / 用户功能块 (KV Script)',
         '程序结构: Siemens FB(有状态)/FC(无状态) → Keyence MACRO(全局)/用户函数；KV-8000 支持结构化文本')
    """)

    # ── Keyence → Siemens ───────────────────────────────────────────────────
    op.execute("""
        INSERT INTO brand_mappings (source_brand, target_brand, item_type, source_value, target_value, description) VALUES
        ('keyence','siemens','io',
         'X0~X511 (输入继电器，十六进制，按模块分配)',
         'Ix.y (I0.0~I127.7)',
         '数字量输入: Keyence X 继电器编号 → Siemens I 点位；需按字节/位拆分(编号÷8=字节，余数=位)'),
        ('keyence','siemens','io',
         'Y0~Y511 (输出继电器，十六进制)',
         'Qx.y (Q0.0~Q127.7)',
         '数字量输出: Keyence Y 继电器 → Siemens Q 点位'),
        ('keyence','siemens','memory',
         'R0~R59999 (内部继电器，按位编号)',
         'Mx.y (Merker位)',
         '位存储器: Keyence R 编号 → Siemens M；R编号÷8=MWx字节偏移，余数=位号'),
        ('keyence','siemens','memory',
         'DM0~DM65535 (数据存储器，16位)',
         'MWx (Merker Word 16位)',
         '字存储器: Keyence DM → Siemens MW；地址可按顺序映射'),
        ('keyence','siemens','memory',
         'FM0~FM32767 (文件存储器，保持型16位)',
         'DB1.DBW0 (数据块，掉电保持)',
         '保持型存储: Keyence FM(掉电保持) → Siemens DB 数据块(RETAIN属性)'),
        ('keyence','siemens','timer',
         'TM0~TM3999 (100ms定时器)',
         'T0 (S_ODT 接通延时, IEC 定时器)',
         '定时器: Keyence TM(100ms) → Siemens IEC T(100ms)；Siemens 支持任意时基'),
        ('keyence','siemens','counter',
         'CM0~CM3999 (计数器存储器)',
         'C0 (CTU 加计数)',
         '计数器: Keyence CM → Siemens CTU；两者预置值写法不同'),
        ('keyence','siemens','communication',
         'EtherNet/IP (端口44818)',
         'PROFINET (端口102)',
         '工业以太网: Keyence EIP → Siemens PROFINET；需协议网关或支持两种协议的 IO-Link Master'),
        ('keyence','siemens','instruction',
         'MOV (传送)',
         'MOVE',
         '数据传送: Keyence MOV → Siemens MOVE Box'),
        ('keyence','siemens','instruction',
         'ADD / SUB (整数加减)',
         'ADD_I / SUB_I',
         '整数运算: Keyence ADD/SUB → Siemens ADD_I/SUB_I')
    """)

    # ── Siemens → Inovance AM600 / Easy ────────────────────────────────────
    op.execute("""
        INSERT INTO brand_mappings (source_brand, target_brand, item_type, source_value, target_value, description) VALUES
        ('siemens','inovance','io',
         'Ix.y (I0.0~I127.7)',
         'Xx.y (X0.0~X127.7)',
         '数字量输入: 格式几乎一致，仅前缀 I→X；点位位置完全对应，移植时直接替换前缀'),
        ('siemens','inovance','io',
         'Qx.y (Q0.0~Q127.7)',
         'Yx.y (Y0.0~Y127.7)',
         '数字量输出: 格式一致，Q→Y 前缀替换；汇川 AM600 物理 IO 模块地址排列相同'),
        ('siemens','inovance','memory',
         'Mx.y (Merker位, M0.0~M8191.7)',
         'M0~M4095 (辅助继电器，按位编号)',
         '位存储器: Siemens Mx.y 按字节偏移 → 汇川 M 按位线性编号(M = byte×8 + bit)；容量注意汇川 M 上限 4095'),
        ('siemens','inovance','memory',
         'MWx (Merker Word 16位)',
         'D0~D9999 (数据寄存器，16位)',
         '字存储器: Siemens MWx → 汇川 D 寄存器；地址可线性映射，汇川容量更大'),
        ('siemens','inovance','memory',
         'MDx (Merker DWord 32位)',
         'D x + D x+1 (两个连续 D 寄存器，32位)',
         '双字: Siemens MDx → 汇川两个连续 D 寄存器；小端序(低16位在低地址)，与西门子一致'),
        ('siemens','inovance','memory',
         'DB1.DBW0 (数据块 Word)',
         'D0~D9999 (全局数据寄存器)',
         '数据块 → 汇川 D 寄存器；汇川无数据块概念，所有 D 寄存器全局可访问'),
        ('siemens','inovance','timer',
         'T0 (S_ODT 接通延时, 100ms分辨率)',
         'T0~T255 (接通延时, 默认100ms, 可配置)',
         '定时器: 语义完全相同；汇川 Easy 系列默认100ms，AM600 支持 1ms 精度配置'),
        ('siemens','inovance','counter',
         'C0 (CTU 加计数 / CTD 减计数)',
         'C0~C255 (加/减计数均支持)',
         '计数器: 两者方向一致，均支持 CTU/CTD；汇川使用 指令+线圈 形式'),
        ('siemens','inovance','communication',
         'PROFINET (IEC 61158, 端口102)',
         'PROFINET (AM600 内置 PN IO 控制器/设备)',
         'PROFINET 完全兼容：AM600 内置 PROFINET，可与西门子 IO 设备或上位机直接通信，无需网关'),
        ('siemens','inovance','communication',
         'S7 协议 (ISO on TCP, 端口102)',
         'Modbus TCP (端口502) 或汇川 TCP 自由口协议',
         '专有协议: Siemens S7 → 汇川不支持 S7；上位机需改用 Modbus TCP 或汇川自有 TCP 协议驱动'),
        ('siemens','inovance','communication',
         'Modbus TCP (标准, 端口502)',
         'Modbus TCP (标准, 端口502)',
         '完全兼容：AM600 / Easy 系列均原生支持 Modbus TCP，寄存器映射略有差异需查汇川手册'),
        ('siemens','inovance','instruction',
         'MOVE (数据传送)',
         'MOV (传送指令)',
         '数据传送: Siemens MOVE → 汇川 MOV；功能完全一致'),
        ('siemens','inovance','instruction',
         'ADD_I / SUB_I (16位整数加减)',
         'ADD / SUB (整数加减)',
         '整数运算: 语义一致；汇川指令集与三菱类似'),
        ('siemens','inovance','instruction',
         'CMP_EQ / CMP_LT / CMP_GT (比较)',
         'CMP (单值比较) / ZCP (区间比较)',
         '比较指令: Siemens 比较 Box → 汇川 CMP/ZCP；指令命名与三菱一致'),
        ('siemens','inovance','instruction',
         'FB/FC 调用 (函数块/函数)',
         'FB (功能块) / 子程序 (PRG)',
         '程序结构: Siemens FB(有状态)/FC(无状态) → 汇川 FB(有实例数据)/PRG 子程序')
    """)

    # ── Inovance → Siemens ─────────────────────────────────────────────────
    op.execute("""
        INSERT INTO brand_mappings (source_brand, target_brand, item_type, source_value, target_value, description) VALUES
        ('inovance','siemens','io',
         'Xx.y (X0.0~X127.7)',
         'Ix.y (I0.0~I127.7)',
         '数字量输入: 格式几乎一致，X→I 前缀替换；汇川 AM600 物理槽位与西门子 I 地址排列相同'),
        ('inovance','siemens','io',
         'Yx.y (Y0.0~Y127.7)',
         'Qx.y (Q0.0~Q127.7)',
         '数字量输出: Y→Q 前缀替换'),
        ('inovance','siemens','memory',
         'M0~M4095 (辅助继电器，按位编号)',
         'Mx.y (Merker位)',
         '位存储器: 汇川 M 线性编号 → Siemens Mx.y；M编号÷8=字节，余数=位'),
        ('inovance','siemens','memory',
         'D0~D9999 (数据寄存器，16位)',
         'MWx (Merker Word 16位)',
         '字存储器: 汇川 D → Siemens MW；地址线性对应'),
        ('inovance','siemens','timer',
         'T0~T255 (接通延时，默认100ms)',
         'T0 (S_ODT 接通延时)',
         '定时器: 语义一致，西门子使用 IEC 定时器 FB'),
        ('inovance','siemens','counter',
         'C0~C255 (加/减计数)',
         'C0 (CTU 加计数 / CTD 减计数)',
         '计数器: 语义一致'),
        ('inovance','siemens','communication',
         'PROFINET (AM600 内置)',
         'PROFINET (内置，S7-1200/1500 标配)',
         '完全兼容：AM600 PN IO 控制器可直接连接西门子 ET200 从站设备'),
        ('inovance','siemens','communication',
         'Modbus TCP (端口502)',
         'Modbus TCP (需 CM 1241 模块或软件实现)',
         'Modbus TCP: 西门子需通过通信模块或用户程序实现 Modbus 主站/从站'),
        ('inovance','siemens','instruction',
         'MOV',
         'MOVE',
         '数据传送'),
        ('inovance','siemens','instruction',
         'ADD / SUB',
         'ADD_I / SUB_I',
         '整数运算')
    """)

    # ── Mitsubishi → Inovance ───────────────────────────────────────────────
    op.execute("""
        INSERT INTO brand_mappings (source_brand, target_brand, item_type, source_value, target_value, description) VALUES
        ('mitsubishi','inovance','io',
         'X0~X1FFF (十六进制输入，X0.0 格式)',
         'X0.0~X127.7 (十进制输入，X字节.位)',
         '数字量输入: 三菱 X 十六进制编号 → 汇川 X 十进制字节.位格式；编号体系不同，需重新分配'),
        ('mitsubishi','inovance','io',
         'Y0~Y1FFF (十六进制输出)',
         'Y0.0~Y127.7 (十进制输出)',
         '数字量输出: 三菱 Y 十六进制 → 汇川 Y 十进制；格式转换同输入'),
        ('mitsubishi','inovance','memory',
         'M0~M8191 (M辅助继电器，按位)',
         'M0~M4095 (辅助继电器，按位)',
         '位存储器: 概念完全一致，命名相同；注意汇川 M 上限仅4095，三菱程序超出部分需改用其他区域'),
        ('mitsubishi','inovance','memory',
         'D0~D7999 (数据寄存器，16位)',
         'D0~D9999 (数据寄存器，16位)',
         '字存储器: 命名相同，直接对应；汇川 D 范围更大，地址可完全复用'),
        ('mitsubishi','inovance','memory',
         'D0+D1 (两个连续D寄存器，32位DWORD)',
         'D x + D x+1 (两个连续 D 寄存器，32位)',
         '双字: 两者均小端序，低16位在低地址；32位指令操作方式完全一致'),
        ('mitsubishi','inovance','timer',
         'T0 (100ms通用) / ST0 (1ms高精度)',
         'T0~T255 (默认100ms，可配置精度)',
         '定时器: 均支持多精度；汇川通过系统参数修改分辨率'),
        ('mitsubishi','inovance','counter',
         'C0 (16位加计数) / DC0 (32位高速)',
         'C0~C255 (加/减计数) / 高速计数器 HC',
         '计数器: 方向一致(均为加计数)；汇川高速计数通过 HSC 功能块实现'),
        ('mitsubishi','inovance','communication',
         'CC-Link IE Field (专有工业以太网)',
         'PROFINET / Modbus TCP (通过协议网关)',
         '工业以太网: CC-Link IE 与汇川不互通，需 HMS Anybus 等网关转换'),
        ('mitsubishi','inovance','communication',
         'MC协议 (SLMP 3E/4E帧, 端口5007)',
         'Modbus TCP (端口502)',
         '专有协议: 三菱 MC 协议 → 汇川 Modbus TCP；上位机驱动需对应修改'),
        ('mitsubishi','inovance','instruction',
         'MOV (传送)',
         'MOV (传送)',
         '数据传送: 命名完全一致，语义相同'),
        ('mitsubishi','inovance','instruction',
         'CMP (单值比较) / ZCP (区间比较)',
         'CMP (单值比较) / ZCP (区间比较)',
         '比较指令: 汇川指令集与三菱保持一致，可直接复用指令名称')
    """)


def downgrade():
    op.execute("""
        DELETE FROM brand_mappings
        WHERE (source_brand = 'siemens' AND target_brand = 'keyence')
           OR (source_brand = 'keyence' AND target_brand = 'siemens')
           OR (source_brand = 'siemens' AND target_brand = 'inovance')
           OR (source_brand = 'inovance' AND target_brand = 'siemens')
           OR (source_brand = 'mitsubishi' AND target_brand = 'inovance')
    """)
